# ENCAPSULATION:
# THE PROCESS OF BINDING DATA MEMBERS AND METHODSS TOGETHER INTO A SINGLE UNIT IS KNOWN
# AS ENCAPSULATION. IT IS ONE OF THE FUNDAMENTAL CONCEPTS OF OBJECT ORIENTED PROGRAMMING. 
# IT IS USED TO HIDE THE INTERNAL REPRESENTATION, OR STATE, OF AN OBJECT FROM THE OUTSIDE. 
# THIS IS ACHIEVED BY MAKING THE DATA MEMBERS PRIVATE AND PROVIDING PUBLIC METHODS TO ACCESS AND MODIFY THEM.

# PYTHON CLASS IS AN GOOD EXAMPLE OF ENCAPSULATION. 
# IN PYTHON, WE CAN MAKE DATA MEMBERS PRIVATE BY PREFIXING THEM WITH TWO UNDERSCORES (__).


# IF ANY COMPONENT FOLLOWS DATA HIDING AND ABSTRACTIONN SUCH TYPE OF COMPONENT IS KNOWN AS ENCAPSULATED
# COMPONENT. ENCAPSULATION IS USED TO HIDE THE INTERNAL REPRESENTATION, OR STATE, OF AN OBJECT FROM THE OUTSIDE.